version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_NAME=tab_project_db
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: tab_project_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
    driver: bridge

