version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: bankappdb
      MYSQL_ROOT_PASSWORD: Test@123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bankapp
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost","-uroot","-pTest@123"]
      interval: 30s
      timeout: 10s
      retries: 5

  bankapp:
    image: bankapp-mini  # Replace with your Spring Boot app image name
    container_name: bankapp
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bankappdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Test@123
    ports:
      - 8080:8080
    networks:
      - bankapp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  bankapp:

volumes:
  mysql_data:

